// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz9IX5VHgUqsnqx3wZKPCp1-gp6K9-HEs',
    appId: '1:916257874968:web:8bb88f189c643ba3634f6d',
    messagingSenderId: '916257874968',
    projectId: 'mejidigital',
    authDomain: 'mejidigital.firebaseapp.com',
    storageBucket: 'mejidigital.appspot.com',
    measurementId: 'G-YZW8ZHJ0WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ-aK45XqR1LtFMTiJTYR_haDL65DqJ2s',
    appId: '1:916257874968:android:c557be6f0eed0b4a634f6d',
    messagingSenderId: '916257874968',
    projectId: 'mejidigital',
    storageBucket: 'mejidigital.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDObkh5pdOCrk3JRlMiLR-MNYxHThTN64o',
    appId: '1:916257874968:ios:d1ec50d034cb0b96634f6d',
    messagingSenderId: '916257874968',
    projectId: 'mejidigital',
    storageBucket: 'mejidigital.appspot.com',
    iosBundleId: 'com.example.meji',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDObkh5pdOCrk3JRlMiLR-MNYxHThTN64o',
    appId: '1:916257874968:ios:d1ec50d034cb0b96634f6d',
    messagingSenderId: '916257874968',
    projectId: 'mejidigital',
    storageBucket: 'mejidigital.appspot.com',
    iosBundleId: 'com.example.meji',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz9IX5VHgUqsnqx3wZKPCp1-gp6K9-HEs',
    appId: '1:916257874968:web:8f3b43f5d21dfcfc634f6d',
    messagingSenderId: '916257874968',
    projectId: 'mejidigital',
    authDomain: 'mejidigital.firebaseapp.com',
    storageBucket: 'mejidigital.appspot.com',
    measurementId: 'G-FD7XFH8JR0',
  );
}
